version: "3"
services:
  nginx:
    image: linojobs/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
  php:
    image: linojobs/php
    build:
      context: ./php
      dockerfile: Dockerfile
